name: victor
dependencies:
  - python
  - pip
  - pylint
  - cython
  - nltk
  - matplotlib
  - pip:
    - numpy
    - scikit-learn
    - tensorflow
    - gensim>=4.0
    - pandas
    - fuzzywuzzy
    - python-Levenshtein